# Generated by Django 5.0.2 on 2024-04-26 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('CorreoElec', models.CharField(blank=True, max_length=12)),
                ('Cell', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_prod', models.CharField(max_length=20)),
                ('Abreviatura', models.CharField(max_length=20)),
                ('Descrip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Transacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Abreviatura', models.CharField(max_length=20)),
                ('Descrip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_Cuenta', models.CharField(max_length=20)),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.clientes')),
                ('id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abreviatura', models.CharField(max_length=10)),
                ('monto', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('Tipo_Transacciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tipo_transacciones')),
                ('id_Cliente_Productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.cliente_productos')),
            ],
        ),
    ]
