# Generated by Django 5.0.2 on 2024-04-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='CorreoElec',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
